shared Concept code into AbstractConcept class and default interface methods
stil4m/mollie-api pull request #40
Opened 2016-11-14 15:08 UTC by tubbynl

i was adding the Mandates concept to this codebase and got tempted into abstracting repetitive code blocks into a AbstractConcept and interfaces

AbstractConcept now

* handles building URL's (and checking on null-id's/path elements)
* handling access on the requestExecutor 
* retaining the API-key and setting that in the requestExecutor

GetById/ListAll/Create/Update/Delete interfaces have default method implementations for these respective mollie methods; because most concepts implement a different subset of these methods the implementations dictate that subset by implementing the required interfaces.

The goals i intent to achieve

* re-use/implement consistently a single list method and it's parameters(and defaults)
* having previous/next methods on all concepts where ListAll is used
* consistently concat url's and check url parameters for null elements/partials (former Util.checkId wasn't consistently used)
* less plumbing with TypeReference or generic Typing in general

This change is imho not a necessity but it makes the impl. easier to change/extend to support more concepts or to update existing shared methods consistently if extra parameters are added in the future. 

It is however breaking on some aspects:

* url creation (AbstractConcept.joinUrl) now throws NullPointerExceptions for null/empty/blank url partials
* the Refunds concept is now created using a PaymentId (consistently as with CustomerPayments and customerId)

2016-11-14 15:23 UTC, tubbynl commented
and perhaps if DynamicClient can be removed more of the plumbing of ApiKey/EndPoint can move towards RequestExecutor. But currently i'm not a aware of how DynamicClient is used in projects.

In my opinion when then api key or endpoint is changed a new Client can be constructed (responsibility of invoking project on how it manages the wrapping service)

2016-11-14 18:42 UTC, stil4m commented
It seems like a good change. Some small improvements are required.  Maybe try out the settings from #28.

2016-11-15 19:17 UTC, tubbynl commented
i've come to appreciate the DynamicClient more now; but the dynamic part only applies on the api-key. The endpoint(base) url and the ObjectMapper are can be final which would allow more http request/serialising plumbing in RequestExecutor

2016-11-16 17:27 UTC, stil4m requested changes

2016-11-16 17:27 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/DynamicClient.java
> +    public Mandates mandates(String apiKey, String customerId) {
I would like to see this as `CustomerMandates`. This would explain the path in the API and the need for the `customerId`. People will know to which this relates.

2016-11-16 17:27 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/DynamicClient.java
> +        return new Refunds(apiKey, endpoint, requestExecutor, paymentId);
I know this is not currently the case, but could refunds be separated into: PaymentRefunds (requiring the payment id) and `Refunds` containing the `ListAll<Refund>`?

2016-11-16 17:27 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/concepts/Update.java
> +public interface Update<R extends Object,O extends Object> extends Concept<R> {
`extends Object` could be removed

2016-11-16 17:27 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/domain/CreateMandate.java
> +            @Nullable String mandateReference) {
Align fields vertically

2016-11-16 17:27 UTC, stil4m commented on src/test/java/nl/stil4m/mollie/concepts/AbstractConceptTest.java
> +    @Test(expected=NullPointerException.class)
I would prefer an `IllegalArgumentException`. `NPE` indicated that **we** made a mistake, `IAE` indicated that the **user** has made a mistake.

2016-11-16 17:27 UTC, stil4m commented on src/test/java/nl/stil4m/mollie/concepts/MandatesIntegrationTest.java
> +        //assertThat(result.getData().getId(),notNullValue());
See #41

2016-11-16 17:27 UTC, stil4m commented on src/test/java/nl/stil4m/mollie/concepts/RefundsIntegrationTest.java
> +        client = new ClientBuilder().withApiKey(VALID_API_KEY).build();
Why not use the `strictClientWithApiKey`?

2016-11-16 17:27 UTC, stil4m commented on src/test/java/nl/stil4m/mollie/concepts/RefundsIntegrationTest.java
> +        ResponseOrError<Page<Refund>> all = refunds.all(Optional.empty(), Optional.empty());
This is a reason why we do want a `Refunds` and `PaymentRefunds`. Consumers of the library will not be able to fetch all the refunds without a payment id...

2016-11-16 17:28 UTC, stil4m commented
Sorry, already reviewed few days ago, but appently github want me to click an additional button 'submit review'. Do not know if you have seen them and some are outdated now.

2016-11-16 19:21 UTC, tubbynl commented on src/test/java/nl/stil4m/mollie/concepts/RefundsIntegrationTest.java
> +        client = new ClientBuilder().withApiKey(VALID_API_KEY).build();
inconsistent/old copy-paste, already did a replacement run on these i thought :)

2016-11-16 19:33 UTC, tubbynl commented on src/test/java/nl/stil4m/mollie/concepts/AbstractConceptTest.java
> +    @Test(expected=NullPointerException.class)
good point; hadn't really considered the API user when choosing the exception type

2016-11-16 19:43 UTC, tubbynl commented on src/main/java/nl/stil4m/mollie/domain/CreateMandate.java
> +            @Nullable String mandateReference) {
i've put them horizontally to be consistent with the other Create\* model classes

2016-11-16 20:08 UTC, tubbynl commented
tnx for the feedback; i think i've covered them with the last push

2016-11-16 21:33 UTC, stil4m requested changes
Last 2 small issues

2016-11-16 21:33 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/concepts/Concept.java
> +    ResponseOrError<Void> requestVoid(HttpUriRequest get) throws IOException;
Maybe rename these params from `get` to `request`

2016-11-16 21:33 UTC, stil4m commented on src/main/java/nl/stil4m/mollie/concepts/AbstractConcept.java
> +    private static final Collector<CharSequence, ?, String> URL_JOINER = Collectors.joining("/");
Cant you replace the question mark with a literal type?

2016-11-16 22:37 UTC, tubbynl commented on src/main/java/nl/stil4m/mollie/concepts/AbstractConcept.java
> +    private static final Collector<CharSequence, ?, String> URL_JOINER = Collectors.joining("/");
it's the java Collectors.joining return type; casting is even more ugly, inlining it might be better

2016-11-18 01:15 UTC, merged

2016-11-18 01:42 UTC, stil4m commented
Just release `2.4.0`.